Repository nextcloud/nextcloud.com, pull requests merged in 2018-11, with the labels that each got.

#990 Signup fixes
  assets/js/pages/signup.js
  assets/js/pages/signup.js.map
  page-signup.php
Labels: bug, signup

#1000 Update my personal discription
  page-team.php
Labels: bug

#1001 Direct link to server-download options
  templates/header-top-navbar.php
Labels: content

#1005 Papercut about-page style
  page-about.php
Labels: content, design
