Repository nextcloud/nextcloud.com, pull requests merged in 2018-12, with the labels that each got.

#1016 Fix @camilasan's LinkedIn link on team page
  page-team.php
Labels: bug

#1011 Small layout fix on team page
  page-team.php
Labels: content, design

#1027 Nextcloud 15 is a supported product version
  page-security.php
Labels: content
