Repository nextcloud/nextcloud.com, pull requests merged in 2018-08, with the labels that each got.

#937 Flex on apps for better mobile view from register update and updated core apps icons
  assets/img/apps/calendar.svg
  assets/img/apps/contacts.svg
  assets/img/apps/files.svg
  assets/img/apps/mail.svg
  assets/img/apps/notes.svg
  assets/img/apps/spreed.svg
  assets/img/apps/tasks.svg
  assets/js/pages/signup.js
  assets/js/pages/signup.js.map
Labels: design

#940 Change user experience talk section
  page-training.php
Labels: enhancement

#943 Statistics retrieval
  config.php.sample
  lib/signup.php
Labels: code
