Repository nextcloud/nextcloud.com, pull requests merged in 2018-10, with the labels that each got.

#971 Fix style of changelog page
  assets/css/custom.css
  assets/css/custom.scss
Labels: enhancement

#973 Improve simple signup
  lib/signup.php
Labels: enhancement, signup

#984 Register fixes for flags
  assets/js/pages/signup.js
  assets/js/pages/signup.js.map
Labels: bug

#989 Use gender-neutral placeholder image
  assets/img/people/person.jpg
Labels: bug, design
